// <auto-generated />
namespace TheBankMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initailmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initailmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202104171410201_initailmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
