// <auto-generated />
namespace TheBankMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BankConfig_Transaction_UserAccount_Enum_ModelsAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BankConfig_Transaction_UserAccount_Enum_ModelsAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202104181108403_BankConfig_Transaction_UserAccount_Enum_ModelsAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
